terminate called after throwing an instance of 'pnm_error'
========= Error: process didn't terminate successfully
